export class ClienteCredito{
    constructor(
        public cred_cli_id: string,
        public cred_mon_sol: string,
        public cred_plazo: string,
        public cred_met: string,
        public cred_des: string,
        public cred_ref1_nom: string,
        public cred_ref1_par: string,
        public cred_ref1_com: string,
        public cred_ref1_dir: string,
        public cred_ref1_tel: string,
        public cred_ref2_nom: string,
        public cred_ref2_par: string,
        public cred_ref2_com: string,
        public cred_ref2_dir: string,
        public cred_ref2_tel: string,
        public cred_ref3_nom: string,
        public cred_ref3_par: string,
        public cred_ref3_com: string,
        public cred_ref3_dir: string,
        public cred_ref3_tel: string,
        public cred_status: string,
        public cred_mon_aut: string,
        public cred_plazo_aut: string,
        public cred_met_aut: string,
        public cred_int_aut: string,
        public cred_garantia: string,
        public cred_asesor: string,
        public cred_fecha_aut: string){
    }
}